services:
  httpd:
    image: httpd:latest
    container_name: host1
    ports:
      - "8080:80"
    networks:
      - app-network

  ansible:
    image: ansible/ansible:ubuntu1404  # Imagem base com Ansible instalado
    container_name: ansible
    volumes:
      - ./scripts:/ansible  # Mapeia o diretório local com os scripts Ansible
    networks:
      - app-network
    command: sleep infinity  # Mantém o container rodando

networks:
  app-network:
    driver: bridge