services:
  httpd:
    image: registry.access.redhat.com/ubi9/httpd-24
    container_name: httpd_rhel
    ports:
      - "80:8080"
    networks:
      - rhel_network

  rabbitmq:
    image: registry.redhat.io/rh-rabbitmq-38/rh-rabbitmq-38-rhel9
    container_name: rabbitmq_rhel
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rhel_network

  postgres:
    image: registry.redhat.io/rhel9/postgresql-15
    container_name: postgres_rhel
    environment:
      POSTGRESQL_USER: admin
      POSTGRESQL_PASSWORD: secret
      POSTGRESQL_DATABASE: mydatabase
    ports:
      - "5432:5432"
    networks:
      - rhel_network

networks:
  rhel_network:
    driver: bridge
